version: '3.8'
services:
    nats:
      image: nats
      expose:
        - "4222"
      ports:
        - "8222:8222"
    service-one-instance-one:
      build: ./service-1
      volumes:
        - ./service-1:/usr/src/app
        - /usr/src/app/node_modules
      ports: 
        - "3000:3000"
      environment:
        PORT: "3000"
        NAME: "service-1"
        INSTANCE: "service-1:instance-1"
        NATS_URL: "nats://nats:4222"
        NATS_QUEUE: "user_queue"
      depends_on:
        - nats
    service-one-instance-two:
      build: ./service-1
      volumes:
        - ./service-1:/usr/src/app
        - /usr/src/app/node_modules
      ports: 
        - "3001:3001"
      environment:
        PORT: "3001"
        NAME: "service-1"
        INSTANCE: "service-1:instance-2"
        NATS_URL: "nats://nats:4222"
        NATS_QUEUE: "user_queue"
      depends_on:
        - nats
    service-two-instance-one:
      build: ./service-2
      volumes:
        - ./service-2:/usr/src/app
        - /usr/src/app/node_modules
      ports: 
        - "3002:3002"
      environment:
        PORT: "3002"
        NAME: "service-2"
        INSTANCE: "service-2:instance-1"
        NATS_URL: "nats://nats:4222"
        NATS_QUEUE: "auth_queue"
      depends_on:
        - nats
    service-three-instance-one:
      build: ./service-3
      volumes:
        - ./service-3:/usr/src/app
        - /usr/src/app/node_modules
      ports: 
        - "3003:3003"
      environment:
        PORT: "3003"
        NAME: "service-3"
        INSTANCE: "service-3:instance-1"
        NATS_URL: "nats://nats:4222"
        NATS_QUEUE: "company_queue"
      depends_on:
        - nats